name: Terraform CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: ğŸ“¦ Terraform Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: â¬‡ï¸ Checkout du code
        uses: actions/checkout@v4

      - name: âš™ï¸ Configuration des identifiants AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::908027392248:role/deploy-terraform
          aws-region: eu-west-1
          audience: sts.amazonaws.com

      - name: ğŸ” Debug - VÃ©rifier lâ€™identitÃ© utilisÃ©e
        run: aws sts get-caller-identity

      - name: â›ï¸ Installer Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.1

      - name: ğŸ“¦ Init + Apply Terraform
        run: |
          terraform fmt
          terraform init
          terraform apply --auto-approve
