name: Terraform CD Pipeline

on:
  push:
    branches:
      - main  # dÃ©ploiement uniquement sur la branche main

permissions:
  id-token: write       # pour OIDC
  contents: read        # pour lire le repo

jobs:
  terraform_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: â¬‡ï¸ Checkout du code
        uses: actions/checkout@v4

      - name: âš™ï¸ Configuration des identifiants AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: eu-west-1

      - name: ğŸ” Debug - VÃ©rifier le rÃ´le AWS utilisÃ©
        run: aws sts get-caller-identity

      - name: â›ï¸ Installer Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.12.1"

      - name: ğŸ“¦ Init + Apply Terraform
        run: |
          terraform fmt
          terraform init
          terraform apply --auto-approve
