name: Terraform CD Pipeline

on:
  workflow_run:
    workflows: ["Build & Push Docker Images"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  create_task:
    name: ğŸ› ï¸ Apply ECS Task Definition
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v4

      - name: âš™ï¸ AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::908027392248:role/deploy-terraform
          aws-region: eu-west-1

      - name: â›ï¸ Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: ğŸ“¦ Terraform Init
        run: terraform init -reconfigure

      - name: ğŸš€ Apply Task Definition
        env:
          TF_VAR_dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          TF_VAR_client_image_tag: v1.0.${{ github.run_number }}
          TF_VAR_server_image_tag: v1.0.${{ github.run_number }}
        run: terraform apply -target=aws_ecs_task_definition.app_task --auto-approve

  deploy_all:
    name: ğŸš€ Full Deploy
    needs: create_task
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v4

      - name: âš™ï¸ AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::908027392248:role/deploy-terraform
          aws-region: eu-west-1

      - name: â›ï¸ Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: ğŸ“¦ Terraform Init
        run: terraform init -reconfigure

      - name: ğŸŒ Apply infrastructure
        env:
          TF_VAR_dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          TF_VAR_client_image_tag: v1.0.${{ github.run_number }}
          TF_VAR_server_image_tag: v1.0.${{ github.run_number }}
        run: terraform apply --auto-approve

      - name: âœ… ALB Output
        run: |
          echo "URL ALB: http://$(terraform output -raw alb_dns_name || echo 'non disponible')"
